### ISSUE TITLE
init via CLI?

### ISSUE THREAD

**Issue by Sispheor** [jeremyephron/simple-gmail#2]
Hi,

Just a question, I haven't had the time to read the doc of the Gmail api but I was wondering if the browser is really mandatory?
There is no way to get the token via CLI?

Thanks.

**Comment by jeremyephron** [comment]
There is no way of authenticating without _some_ browser interaction (or would be unnecessarily complicated to do otherwise), due to Google's security precautions. There are other ways of authenticating that require you to change/allow things in your Google account security settings (so browser interaction would be required at that stage).

Using a token as I do here is generally the safest method to interact with your Gmail account. I know it's a bit of a bummer, but you only have to do it once.

If I'm mistaken for any reason and there is a better way to get around authentication, feel free to reopen the issue and let me know.
