### ISSUE TITLE
Add v3.1 to Releases tab

### ISSUE THREAD

**Issue by roib20** [jeremyephron/simple-gmail#22]
Could you please add v3.1 to the Releases tab under GitHub? Of course the new version is already available on pip but having it on GitHub as well will allow another way for people to get the new release (without having to clone the master branch).

BTW, absolutely love the new release. A short test I did shows a query that used to take 4 minutes (in simplegmail v3.0) now takes just 20 seconds (in simplegmail v3.1.2). That's over 10 times faster! Very impressive.

**Comment by jeremyephron** [comment]
@roib20 I just added [release v3.1.2](https://github.com/jeremyephron/simple-gmail/releases/tag/v3.1.2), thanks for reminding me. I will make sure to consistently upload them in the future. I'm glad you are having a good experience with it; it's unfortunate I didn't add that feature sooner, it was delayed for the silliest of reasons (this [one line](https://github.com/jeremyephron/simple-gmail/commit/b51917a536356c814ec2dc7ed8f60d954fda8379#diff-fa466a860f66e21a109883a3f1766f02ffce127ae892464bf1d526bc32990f07R793) was the fix for what was holding up the release :/ ).
